spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cas
    username: postgres
    password: toor
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: validate  # What to do with existing schema
    show-sql: true  # logging for sql statements
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

domain: "ourbrandname.com"

jwt:
  tokenName: "Bearer"
  keys:
    private: "Private key"
    public: "Public key"
  lifetime: 24 # hours
  claims:
    roles: "ROLES"

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui.html
    layout:
