spring:
  datasource:
    url:  jdbc:h2:file:./src/main/resources/database/db;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS auth
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
          hibernate:
            jdbc.lob.non_contextual_creation: true
  h2:
    console.enabled: true

domain: "ourbrandname.com"

jwt:
  tokenName: "Bearer"
  issuer: "cas.ourbrandname.com"
  secret: "SJ/0nkbdrSukzOKpJC8+i9r2DDoLgskqfH0bGiJt8pk=" # base64 encoded
#  TODO: Go with asymmetric approach
  keys:
    private: "Private key"
    public: "Public key"
  lifetime: 24 # hours
  claims:
    roles: "ROLES"

springdoc:
  api-docs:
    path: "/api/v1/docs/api-docs"
  swagger-ui:
    path: "/api/v1/docs/swagger-ui.html"
